
services:
  microtube:
    image: v4containers/microtube/api
    mem_limit: 2gb
    build:
      context: ./MicroTube
    depends_on:
       mssql:
         condition: service_started
       elasticsearch:
        condition: service_healthy
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:7146;
     - ASPNETCORE_Kestrel__Certificates__Default__Password=password
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/usr/local/share/ca-certificates/localhost.pfx
    ports:
      - "7146:7146"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ./Shared/Dev_Certificates/:/usr/local/share/ca-certificates
  client-angular:
    image: v4containers/microtube/client/angular
    mem_limit: 2gb
    ports: 
      - "44466:44466"
    develop:
      watch:
        - action: sync
          path: ./MicroTube.Client.Angular
          target: ./app
    build:
      context: ./MicroTube.Client.Angular
      dockerfile: ./Dockerfile.dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ./Shared/Dev_Certificates/:/usr/local/share/ca-certificates
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    mem_limit: 2gb
    container_name: sql-server
    hostname: sql-server
    environment: 
     - ACCEPT_EULA=true
     - MSSQL_SA_PASSWORD=devpassword12345++
    ports:
      - "1433:1433"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    mem_limit: 400mb
    container_name: Azurite
    hostname: azurite
    ports:
      - "10000:10000"
    entrypoint: ["azurite-blob", "--blobHost", "0.0.0.0", "--blobPort", "10000"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    mem_limit: 3gb
    container_name: elasticsearch
    hostname: elasticsearch
    ports: 
      - "9200:9200"
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
     test:
       [
         "CMD-SHELL",
         "curl -s http://elasticsearch:9200 >/dev/null || exit 1",
       ]
     interval: 5s
     timeout: 10s
     retries: 120
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    mem_limit: 1gb
    container_name: kibana
    hostname: kibana
    ports: 
      - "5601:5601"
    environment:
      - XPACK_SECURITY_ENABLED=false
  devmail:
    image: rnwood/smtp4dev
    mem_limit: 250mb
    container_name: devmail
    hostname: devmail
    ports:
     - "5000:80"
     - "587:587"
    environment:
     - ServerOptions__Urls=https://*:80
     - ServerOptions__Port=587
     - ServerOptions__HostName=devmail
     - ServerOptions__TlsMode=StartTls
     - ServerOptions__TlsCertificate=/usr/local/share/ca-certificates/devmail.crt
     - ServerOptions__TlsCertificatePrivateKey=/usr/local/share/ca-certificates/devmail.key
     - ServerOptions__SmtpAllowAnyCredentials=false
     - ServerOptions__AuthenticationRequired=true
     - ServerOptions__Users__0__Username=no-reply@devmail
     - ServerOptions__Users__0__Password=no-reply-password
    volumes:
      - ./Shared/Dev_Certificates/:/usr/local/share/ca-certificates
      - smtp4dev-data:/smtp4dev
volumes:
  smtp4dev-data: