
services:
  microtube:
    image: v4containers/microtube/api
    mem_limit: 4gb
    build:
      context: ./MicroTube
    depends_on:
       mssql:
         condition: service_started
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:7146;
     - ASPNETCORE_Kestrel__Certificates__Default__Password=password
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/microtube.pfx
    ports:
      - "7146:7146"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  client-angular:
    image: v4containers/microtube/client/angular
    ports: 
      - "44466:44466"
    develop:
      watch:
        - action: sync
          path: ./MicroTube.Client.Angular
          target: ./app
    build:
      context: ./MicroTube.Client.Angular
      dockerfile: ./Dockerfile.dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    mem_limit: 3gb
    container_name: sql-server
    hostname: sql-server
    environment: 
     - ACCEPT_EULA=true
     - MSSQL_SA_PASSWORD=devpassword12345++
    ports:
      - "1433:1433"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    mem_limit: 1gb
    container_name: Azurite
    hostname: azurite
    ports:
      - "10000:10000"
    entrypoint: ["azurite-blob", "--blobHost", "0.0.0.0", "--blobPort", "10000"]
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    mem_limit: 3gb
    container_name: elasticsearch
    hostname: elasticsearch
    ports: 
      - "9200:9200"
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.audit.logfile.events.emit_request_body = true
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    hostname: kibana
    ports: 
      - "5601:5601"
    environment:
      - XPACK_SECURITY_ENABLED=false