name: Build & Deploy Angular Client
on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
jobs:
  build-and-push-docker-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.6.1
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
          registry: v4containers.azurecr.io
          username: ${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
    - name: Build & Push API
      uses: docker/build-push-action@v6.7.0
      with:
        cache-from: gha
        cache-to: type=gha, mode=max
        push: true
        file: MicroTube.Client.Angular/Dockerfile.prod
        context: MicroTube.Client.Angular/
        tags: |
            v4containers.azurecr.io/${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}/microtube/client/angular:latest
            v4containers.azurecr.io/${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}/microtube/client/angular:${{ github.sha }}
