name: Build & Deploy API
on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Install Azurite
      id: azuright
      uses: potatoqualitee/azuright@v1.1
    - name: Setup FFmpeg
      uses: federicocarboni/setup-ffmpeg@v3.1
    - name: Restore MicroTube dependencies
      run: dotnet restore ./MicroTube/MicroTube.csproj
    - name: Build MicroTube
      run: dotnet build ./MicroTube/MicroTube.csproj --no-restore
    - name: Restore MicroTube.Tests dependencies
      run: dotnet restore ./MicroTube.Tests/MicroTube.Tests.csproj
    - name: Build MicroTube.Tests
      run: dotnet build ./MicroTube.Tests/MicroTube.Tests.csproj --no-restore
    - name: Test
      run: dotnet test ./MicroTube.Tests/MicroTube.Tests.csproj --no-build
  build-and-deploy-container-app:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Azure Login
      - uses: Azure/login@v2.2.0
        with:
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      - name: Build and Push to Container App
      - uses: Azure/container-apps-deploy-action@v2
        with: 
          appSourcePath: ./MicroTube
          dockerfilePath: ./MicroTube/Dockerfile
          registryUrl: v4containers.azurecr.io
          registryUsername: ${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}    
          registryPassword: ${{ secrets.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
          containerAppName: microtube-ca
          resourceGroup: MicroTube
          imageToBuild: v4containers.azurecr.io/microtube-ca:${{ github.sha }}
  #build-and-push-docker-container:
    #runs-on: ubuntu-latest
    #needs: test
    #steps:
    #- uses: actions/checkout@v4
    #- name: Docker Setup Buildx
    #  uses: docker/setup-buildx-action@v3.6.1
    #- name: Docker Login
    #  uses: docker/login-action@v3.3.0
    #  with:
    #      registry: v4containers.azurecr.io
     #     username: ${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}
      #    password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
    #- name: Build & Push API
     # uses: docker/build-push-action@v6.7.0
     # with:
      #  cache-from: gha
      #  cache-to: type=gha, mode=max
      #  push: true
       # file: MicroTube/Dockerfile
       # context: MicroTube/
       # tags: |
       #     v4containers.azurecr.io/${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}/microtube/api:latest
       #     v4containers.azurecr.io/${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}/microtube/api:${{ github.sha }}
