name: Build & Deploy API
on:
  pull_request:
    branches: [ "master", "development" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Install Azurite
      id: azuright
      uses: potatoqualitee/azuright@v1.1
    - name: Setup FFmpeg
      uses: federicocarboni/setup-ffmpeg@v3.1
    - name: Restore MicroTube dependencies
      run: dotnet restore ./MicroTube/MicroTube.csproj
    - name: Build MicroTube
      run: dotnet build ./MicroTube/MicroTube.csproj --no-restore
    - name: Restore MicroTube.Tests dependencies
      run: dotnet restore ./MicroTube.Tests/MicroTube.Tests.csproj
    - name: Build MicroTube.Tests
      run: dotnet build ./MicroTube.Tests/MicroTube.Tests.csproj --no-restore
    - name: Test
      run: dotnet test ./MicroTube.Tests/MicroTube.Tests.csproj --no-build
  build-and-deploy-container-app:
    needs: test
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        creds: ${{secrets.AZURE_CREDS}}
    - name: Build and Push to Container App
      uses: Azure/container-apps-deploy-action@v2
      with: 
        appSourcePath: ./MicroTube
        dockerfilePath: Dockerfile
        registryUrl: v4containers.azurecr.io
        registryUsername: ${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}    
        registryPassword: ${{ secrets.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
        containerAppName: microtube-ca
        resourceGroup: MicroTube
        imageToBuild: v4containers.azurecr.io/microtube-ca:${{ github.sha }}
