name: Trigger auto deployment for microtube-client-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ development ]
    paths:
    - '**'
    - '.github/workflows/microtube-client-ca-AutoDeployTrigger-be3bdd26-4e91-4e9d-abd1-5c45d030575f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MICROTUBECLIENTCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MICROTUBECLIENTCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MICROTUBECLIENTCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/MicroTube.Client.Angular/Dockerfile.prod
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: v4containers.azurecr.io
          registryUsername: ${{ secrets.MICROTUBECLIENTCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MICROTUBECLIENTCA_REGISTRY_PASSWORD }}
          containerAppName: microtube-client-ca
          resourceGroup: MicroTube
          imageToBuild: v4containers.azurecr.io/microtube-client-ca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


