CREATE TABLE [dbo].[UsedRefreshToken]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[SessionId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.AppUserSession(Id) ON DELETE CASCADE,
	[Token] nvarchar(50) NOT NULL
)
