CREATE TABLE [dbo].[VideoDislike]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.AppUser(Id),
	[VideoId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Video(Id),
	[Time] DATETIME NOT NULL,
	UNIQUE([UserId], [VideoId])
)
