CREATE TABLE [dbo].[VideoUploadProgress]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[VideoId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Video(Id) ON DELETE CASCADE,
	[LastReportedTimestamp] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
    [Progress] FLOAT NOT NULL DEFAULT 0
)
