CREATE TABLE [dbo].[VideoWatch]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
	[Ip] VARCHAR(100) NOT NULL UNIQUE, 
    [VideoId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Video(Id)
)
