CREATE TABLE [dbo].[Video]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Title] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(1000) DEFAULT NULL,
	[UploaderId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.AppUser(Id),
	[Url] NVARCHAR(100) NOT NULL,
	[ThumbnailUrls] VARCHAR(MAX) DEFAULT NULL, 
    [SnapshotUrls] VARCHAR(MAX) NULL DEFAULT NULL,
	[UploadTime] DATETIME NOT NULL
)
