CREATE TABLE [dbo].[Video]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Title] NVARCHAR(50) NOT NULL,
	[UploaderId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.AppUser(Id),
	[FileMetaId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.FileMeta(Id) ON DELETE CASCADE
)
